#!/bin/bash

## Name:     pacxter v0.1b
## Author:   grimi (grimi at poczta dot fm)
## About:    simple xterm "gui" for ArchLinux to installing packages
## License:  GNU GPL v3
## Required: pacman,xterm
## Optional: sudo



## Some variables ##
PACMAN="/usr/bin/pacman"
XTERM="/usr/bin/xterm"
SUDO="/usr/bin/sudo"
NAME="${0##*/}"



## Lang messages ##
case "${LANG%_*}" in
  pl)
    MSG_PASSROOT="Podaj hasło roota: "
    MSG_PASS="Podaj hasło: "
    MSG_HIT="Naciśnij ::ENTER::"
    MSG_USAGE="*** Składnia: $NAME [-t] <nazwa paczki> ***\n\t  -t: wykonaj w xterm\n"
    MSG_WAITPAC="Czekam na inny proces pacmana ...\n"
  ;;
  *)
    MSG_PASSROOT="Enter root password: "
    MSG_PASS="Enter password: "
    MSG_HIT="Press ::ENTER::"
    MSG_USAGE="*** Usage: $NAME [-t] <package name> ***\n\t  -t: exec in xterm\n"
    MSG_WAITPAC="Waiting for another pacman process...\n"
  ;;
esac


## Current term mode ##
if [[ $1 == "-t" ]]; then
  exec $XTERM -g 74x16 -T "..:: $NAME ::.." -e "echo ; $0 '$2' ; echo -e '\n$MSG_HIT' ; read"
fi


## Checkout pacman running
if [[ -f /var/lib/pacman/db.lck ]]; then
  echo -e ":: $MSG_WAITPAC"
  while (pidof >/dev/null /usr/bin/pacman); do
    sleep 1
  done
fi

## Select proper action ##
if [[ -z $1 ]]; then
  echo -e "$MSG_USAGE"
elif [[ $USER == "root" ]]; then
  $PACMAN 2>&1 -U "$1"
elif [[ $(($SUDO -v && $SUDO -n -l -U $USER $PACMAN -U) 2>/dev/null) == "$PACMAN -U" ]]; then
  $SUDO -p "$MSG_PASS" $PACMAN 2>&1 -U "$1"
else
  echo -n "$MSG_PASSROOT"
  /bin/su 2>/dev/null -c 'echo ; $PACMAN 2>&1 -U "$1"'
fi


# vim:set ts=2 sw=2 sts=2 et:

