#!/bin/bash
# Name:    uprepo
# About:   script for Arch Linux to display pacman updates in conky
# Author:  grimi < grimi at poczta do fm >
# License: GNU GPL v3



case ${LANG%_*} in
    pl) USAGEMSG="Składnia: [-a(tryb AUR: cower jako wrapper)] [-n(bez koloru)]"
        NOAVAILMSG="niedostępne"
    ;;

     *) USAGEMSG="Usage: [-a(AUR mode: cower as wrapper)] [-n(nocolors)]"
        NOAVAILMSG="not available"
    ;;
esac

if [ "$1" = "-h" ]; then
   echo "$USAGEMSG"
   exit 1
fi

if [ "$1" != "-a" ]; then
    PACNR=$(LANG=C pacman -Qqu --color=never | grep -Ev "^($ignore)$" | wc -l)
else
    ping -w 3 -c 1 aur.archlinux.org >/dev/null ; AUROL=$?
    COWER=$(type -fp cower)
    if [[ $AUROL -eq 0 && $COWER ]]; then
        PACNR=$(LANG=C $COWER -u --color=never | wc -l)
    else
        PACNR="$NOAVAILMSG"
    fi
    shift
fi

if [ "$1" != "-n" ]; then
   case $PACNR in
      0)       SETCOL='${color white}' ;;
      [1-4])   SETCOL='${color yellow}' ;;
      [5-9])   SETCOL='${color orange}' ;;
      *)       SETCOL='${color red}' ;;
   esac
   RESCOL='${color}'
fi


SetMsg() {
   case $PACNR in
      0) MSG="no updates" ;;
      1) MSG="1 package" ;;
      *) MSG="$PACNR packages" ;;
   esac
}

SetMsg_pl() {
    NR1=${PACNR:${#PACNR}-1}
    NR2=${PACNR:${#PACNR}-2}
    if [ $PACNR = 0 ];then
        MSG="aktualne"
    elif [ $PACNR = 1 ];then
        MSG="1 paczka"
    elif [ $NR1 -ge 2 ] && [ $NR1 -le 4 ] && [ $[$NR2-$NR1] -ne 10 ]; then
        MSG="$PACNR paczki"
    else
        MSG="$PACNR paczek"
    fi
}

if [ "$PACNR" != "$NOAVAILMSG" ]; then
    case ${LANG%_*} in
        pl) SetMsg_pl;;
        *)  SetMsg;;
    esac
fi

echo ${SETCOL}${MSG}${RESCOL}


